#pragma kernel CalStemBSplineCurveResult
#pragma kernel CalStemGrowth

#define NUMTHRED_VAL 256

struct StemVertex{
    float3 vertice;
    float3 tangent;
    float3 normal;
    float3 bioNormal;
    int index;
};

//花の数など
struct StemManage{
    int flowerCount;
    int flowerStartIndex;
    int leafCount;
    int leafStartIndex;
};

//花や茎を生成するための情報を載せる構造体
struct StemData{
    int index;
    float3 position;
    float3 tangent;
    float3 normal;
    float3 bioNormal;
};

RWStructuredBuffer<float3> _read_stemBasePosition_buffer;
RWStructuredBuffer<StemVertex> _read_stemResult_buffer;
RWStructuredBuffer<StemVertex> _write_stemResult_buffer;
RWStructuredBuffer<StemVertex> _read_stemVertex_buffer;
RWStructuredBuffer<StemVertex> _write_stemVertex_buffer;
RWStructuredBuffer<StemManage> _read_stemManage_buffer;
RWStructuredBuffer<StemManage> _write_stemManage_buffer;
RWStructuredBuffer<StemData> _read_stemDataFlower_buffer;
RWStructuredBuffer<StemData> _write_stemDataFlower_buffer;
RWStructuredBuffer<StemData> _read_stemDataLeaf_buffer;
RWStructuredBuffer<StemData> _write_stemDataLeaf_buffer;

RWStructuredBuffer<float4x4> _write_stem_debug_bufer;

int _contPosArrayLength;
float4 _controlPoints[6];
float _knotMin;
float _knotMax;
float _tWidth;
int _stemVertexCount;

float GetBasisFunctionFour(float u[10],int j,int k,float t){
    float w1=0.0;
    float w2=0.0;

    if(u[j]<t&&t<=u[j+1]){
        return 1.0;
    }else{
        return 0.0;
    }
    
}

float GetBasisFunctionThird(float u[10],int j,int k,float t){
    float w1=0.0;
    float w2=0.0;

    //if(k==0){
        if(u[j]<t&&t<=u[j+1]){
            return 1.0;
        }else{
            return 0.0;
        }
    // }else{
    //     if(u[j+k+1]-u[j+1]!=0.0){
    //         w1=GetBasisFunctionFour(u,j+1,k-1,t)*(u[j+k+1]-t)/(u[j+k+1]-u[j+1]);
    //     }

    //     if((u[j+k]-u[j])!=0.0){
    //         w2=GetBasisFunctionFour(u,j,k-1,t)*(t-u[j])/(u[j+k]-u[j]);
    //     }

    //     return w1+w2;
    // }
    
}

float GetBasisFunctionSecond(float u[10],int j,int k,float t){
    float w1=0.0;
    float w2=0.0;

    if(k==0){
        if(u[j]<t&&t<=u[j+1]){
            return 1.0;
        }else{
            return 0.0;
        }
    }else{
        if(u[j+k+1]-u[j+1]!=0.0){
            w1=GetBasisFunctionThird(u,j+1,k-1,t)*(u[j+k+1]-t)/(u[j+k+1]-u[j+1]);
        }

        if((u[j+k]-u[j])!=0.0){
            w2=GetBasisFunctionThird(u,j,k-1,t)*(t-u[j])/(u[j+k]-u[j]);
        }

        return w1+w2;
    }
    
}

float GetBasisFunction(float u[10],int j,int k,float t){
    float w1=0.0;
    float w2=0.0;

    if(k==0){
        if(u[j]<t&&t<=u[j+1]){
            return 1.0;
        }else{
            return 0.0;
        }
    }else{
        if(u[j+k+1]-u[j+1]!=0.0){
            w1=GetBasisFunctionSecond(u,j+1,k-1,t)*(u[j+k+1]-t)/(u[j+k+1]-u[j+1]);
            //w1=5.0;
        }

        if((u[j+k]-u[j])!=0.0){
            w2=GetBasisFunctionSecond(u,j,k-1,t)*(t-u[j])/(u[j+k]-u[j]);
            //w2=5.0;
        }

        return w1+w2;
    }
    
}

void Cal_BSplineCurve(inout float3 S[16],float4 controlPoints[6],float knotMin,float knotMax,float tWidth,uint3 DID){
    int p=6;
    int n=3;
    int m=p+n+1;
    //Debug.Log("m: "+m);
    // m : 10

    //GetKnotVector
    float u[10];
    int knotN=n+1;
    
    for(int i=0;i<m;i++){
        if(i>=0&&i<knotN){
            u[i]=knotMin;
            // u[i]=1192;
        }else if(i>=knotN&&i<(m-knotN)){
            int knotWidth=m-knotN*2;
            float knotVal=(knotMax-knotMin)/(float)(knotWidth+1);
            knotVal=knotVal*(float)(i-knotN+1);
            u[i]=knotVal;
            // u[i]=1192;
        }else if(i>=(m-knotN)&&i<m){
            u[i]=knotMax;
            // u[i]=1192;
        }

        //u[i]=1192;
    }
    
    float tDelta[16];
    int num=(int)((knotMax-knotMin)/tWidth);
    for(int i=0;i<num;i++){
        tDelta[i]=(float)(tWidth*i);
    }

    for(int i=0;i<16;i++){
        S[i]=float3(0,0,0);
    }
    
    S[0]=controlPoints[0].xyz;
    
    for(int i=1;i<16;i++){
        for(int j=0;j<p;j++){
            float b=GetBasisFunction(u,j,n,tDelta[i]);
            S[i]=S[i]+controlPoints[j].xyz*b;
        }
    }

    //  _write_stem_debug_bufer[DID.x]=float4x4(
    //     float4(u[0],u[1],u[2],u[3]),
    //     float4(u[4],u[5],u[6],u[7]),
    //     float4(u[8],u[9],_tWidth,tWidth),
    //     float4(_knotMin,_knotMax,knotMin,knotMax)
    // );

// Debug.Log("u.Length:"+u.Length);
    //u: 10
    // Debug.Log("tDelta.Count: "+tDelta.Count);
    //tDelta.Count: 19
    // Debug.Log("S.Count: "+S.Count);
    //S.Count: 19

   // return S;
    

}


[numthreads(NUMTHRED_VAL,1,1)]
void CalStemBSplineCurveResult(
    uint3 DID : SV_DISPATCHTHREADID
){
    float3 stemBasePosition[16];
    for(int i=0;i<16;i++){
        stemBasePosition[i]=float3(0,0,0);
    }

    float3 resampleControlPoints[6];
    int stemGroupID=floor(DID.x/_stemVertexCount);
    int idInMyStem=DID.x-stemGroupID*_stemVertexCount;

    Cal_BSplineCurve(stemBasePosition,_controlPoints,_knotMin,_knotMax,_tWidth,DID);
    
    StemVertex stemO;
    stemO.vertice=stemBasePosition[idInMyStem]+_read_stemBasePosition_buffer[stemGroupID];
    stemO.tangent=float3(0,0,0);
    stemO.normal=float3(0,0,0);
    stemO.bioNormal=float3(0,0,0);

    if(idInMyStem>0&&idInMyStem<16-1){
        float3 stemTangent=normalize(stemBasePosition[idInMyStem+1]-stemBasePosition[idInMyStem-1]);
        float3 stemNormal=normalize(cross(stemTangent,float3(1,0,0)));
        float3 stemBioNormal=normalize(cross(stemTangent,stemNormal));


        stemO.tangent=stemTangent;
        stemO.normal=stemNormal;
        stemO.bioNormal=stemBioNormal;

        // _write_stem_debug_bufer[DID.x]=float4x4(
        //     float4(stemO.vertice,0),
        //     float4(stemBasePosition[idInMyStem+1],0),
        //     float4(stemBasePosition[idInMyStem-1],0),
        //     float4(idInMyStem,0,0,0)
        // );

        _write_stem_debug_bufer[DID.x]=float4x4(
            float4(stemO.vertice,0),
            float4(stemTangent,0),
            float4(stemNormal,0),
            float4(stemBioNormal,0.0)
        );

    }

    stemO.index=idInMyStem;

    _write_stemResult_buffer[DID.x]=stemO;

    // _write_stem_debug_bufer[DID.x]=float4x4(
    //     float4(stemO.vertice,0),
    //     float4(stemO.tangent,0),
    //     float4(stemO.normal,0),
    //     float4(stemO.bioNormal,stemO.index)
    // );

  

}

[numthreads(NUMTHRED_VAL,1,1)]
void CalStemGrowth(
     uint3 DID : SV_DISPATCHTHREADID
){

}