#pragma kernel CalFlowerGrowth

#define NUMTHRED_VAL 256

struct StemData{
    int resampleIndex;
    int resampleIndexInStem;
    float3 position;
    float3 tangent;
    float3 normal;
    float3 bioNormal;
    int renderFlag;
    float lifeTime;
};

struct StemVertex{
    float3 vertice;
    float3 tangent;
    float3 normal;
    float3 bioNormal;
    int index;
};

struct StemManage{
    float stemLifeVal;
    float stemWaitTime;
    float signNum;
    int manageLifeCountFlag;
    int flowerCount;
    int flowerStartIndex;
    int leafCount;
    int leafStartIndex;
};

RWStructuredBuffer<StemData> _write_stemDataFlower_buffer;
RWStructuredBuffer<StemVertex> _read_stemVertex_buffer;
RWStructuredBuffer<StemManage> _read_stemManage_buffer;

RWStructuredBuffer<float4x4> _debug_buffer;

int _stemVertexCount;
float _isFloweringTime;
float _DTime;

[numthreads(NUMTHRED_VAL,1,1)]
void CalFlowerGrowth(
    uint3 DID : SV_DISPATCHTHREADID
){
    StemData sData;
    StemManage sManage=_read_stemManage_buffer[DID.x];
    int resampleIndexInStem=_stemVertexCount-1;
    int stemIndex=DID.x;
    int resampleIndex=stemIndex*_stemVertexCount+resampleIndexInStem;
    StemVertex sVertex=_read_stemVertex_buffer[resampleIndex];

    sData.resampleIndex=resampleIndex;
    sData.resampleIndexInStem=resampleIndexInStem;
    sData.position=sVertex.vertice;
    sData.tangent=sVertex.tangent;
    sData.normal=sVertex.normal;
    sData.bioNormal=sVertex.bioNormal;
    sData.renderFlag=0;
    sData.lifeTime=(sin(_DTime)+1.0)*0.5;

    if(sManage.stemLifeVal>_isFloweringTime){
        sData.renderFlag=1;
    }    

    _write_stemDataFlower_buffer[DID.x]=sData;

    _debug_buffer[DID.x]=float4x4(
        float4(sData.resampleIndex,sData.resampleIndexInStem,sData.renderFlag,sData.lifeTime),
        float4(sData.position,stemIndex),
        float4(sData.tangent,_stemVertexCount),
        float4(sData.normal,0)
    );

}