#pragma kernel CalPetalGPUParticle

#define NUMTHREADS_VAL 256

struct PetalAnimation{
    float petalLifeTime;
    float3 position;
    float3 rotation;
    float4 petalColor;
    float petalAngular;
};

RWStructuredBuffer<PetalAnimation> _write_petalAnim_buffer;
RWStructuredBuffer<float3> _read_petalBasePosition_buffer;

[numthreads(NUMTHREADS_VAL,1,1)]
void CalPetalGPUParticle(
    uint3 DID : SV_DISPATCHTHREADID
){

}