#pragma kernel CalVector
#pragma kernel ResultVector

#define NUMTHREADS_X_NUM 256

struct Butterfly{
    float3 position;
    float3 velocity;
};

RWStructuredBuffer<Butterfly> _boids_data_write;
RWStructuredBuffer<Butterfly> _boids_data_read;
RWStructuredBuffer<float3> _boids_force_write;
RWStructuredBuffer<float3> _boids_force_read;

RWStructuredBuffer<float4x4> _debugBuffer;

int _butterfly_count;
float _maxBoidsDist;
float _DTime;
float _Time;
float _maxBoidsField;
float _centerPosPower;
float _NoiseValue;

float _joinPower;
float _separatePower;
float _alignmentPower;

float _joinDisMin;
float _separateDistMin;
float _alignmentDistMin;

groupshared Butterfly butterfly_data[NUMTHREADS_X_NUM];

float3 TurnButterfly(float3 pos,float3 vel,float uid){
    float3 turnVel=float3(0,0,0);
     
    float seed=2.5;
    
    if(pos.x<-1.0*_maxBoidsField){
        vel.x+=seed*abs(vel.x);
    }
     if(pos.x>_maxBoidsField){
        vel.x-=seed*abs(vel.x);
    }
    
    if(pos.y<-1.0*_maxBoidsField){
        vel.y+=seed*abs(vel.y);
    }
     if(pos.y>_maxBoidsField){
        vel.y-=seed*abs(vel.y);
    }

    if(pos.z<-1.0*_maxBoidsField){
        vel.z+=seed*abs(vel.z);
    }
     if(pos.z>_maxBoidsField){
        vel.z-=seed*abs(vel.z);
    }

    return vel;
}

float rand(float2 st){
    return frac(sin(dot(st,float2(12.9898,78.233)))*43758.5453);
}


float perlinNoise(float2 seeds)
{
    float2 i = floor(seeds);
    float2 f = frac (seeds);
    float2 i00 = i + float2(0, 0);
    float2 i10 = i + float2(1, 0);
    float2 i01 = i + float2(0, 1);
    float2 i11 = i + float2(1, 1);
    float2 f00 = f - float2(0, 0);
    float2 f10 = f - float2(1, 0);
    float2 f01 = f - float2(0, 1);
    float2 f11 = f - float2(1, 1);
    float2 g00 = normalize(-1 + 2 * rand(i00));
    float2 g10 = normalize(-1 + 2 * rand(i10));
    float2 g01 = normalize(-1 + 2 * rand(i01));
    float2 g11 = normalize(-1 + 2 * rand(i11));
    float2 v00 = dot(g00, f00);
    float2 v10 = dot(g10, f10);
    float2 v01 = dot(g01, f01);
    float2 v11 = dot(g11, f11);
    float2 p = smoothstep(0, 1, f);
    float v00v10 = lerp(v00, v10, p.x);
    float v01v11 = lerp(v01, v11, p.x);
    return lerp(v00v10, v01v11, p.y) * 0.5 + 0.5;
}

[numthreads(NUMTHREADS_X_NUM,1,1)]
void CalVector(
    uint3 GID : SV_GROUPTHREADID,
    uint3 DID : SV_DISPATCHTHREADID
){
    Butterfly my_butterfly_data=_boids_data_read[DID.x];
     float3 my_position=my_butterfly_data.position;
     float3 my_velocity=my_butterfly_data.velocity;

    float3 joinVal=float3(0,0,0);
    float3 separateVal=float3(0,0,0);
    float3 alignmentVal=float3(0,0,0);

    float joinCount=0;
    float separateCount=0;
    float alignmentCount=0;

    float3 joinPosSum=float3(0,0,0);
    float3 separateVectorSum=float3(0,0,0);
    float3 alignmentVectorSum=float3(0,0,0);

    float3 joinForce=float3(0,0,0);
    float3 separateForce=float3(0,0,0);
    float3 alignmentForce=float3(0,0,0);

    float3 result_velocity=(float3)my_velocity;

     float3 centerPos=float3(0,0,0);
     float smallT=0.1;
    centerPos=float3(cos(_Time*smallT)*_centerPosPower,0.,sin(_Time*smallT)*_centerPosPower);
    centerPos=float3(0,0,_Time*_centerPosPower);

    float disMin=100000000.0;
    float disMax=-10000000.0;

    float speed=0.005;
    
    [loop]
    for(int i=0;i<_butterfly_count;i+=255){
        butterfly_data[GID.x]=_boids_data_read[i+GID.x];
        
        GroupMemoryBarrierWithGroupSync();

        for(int q=0;q<255;q++){
            float3 other_position=butterfly_data[q].position;
            float3 other_velocity=butterfly_data[q].velocity;

            float dis=length(other_position-my_position);
            dis=abs(dis);

            //join
            if(dis>0&&dis<=_joinDisMin){
                float3 dirPos=other_position;
                joinPosSum+=dirPos*(1.0/dis);
                joinCount++;
            }
            //separate
            if(dis>0&&dis<=_separateDistMin){
                float3 dirVector=other_position-my_position;
                separateVectorSum-=dirVector*(1.0/dis);
                separateCount++;
            }
            //alignment
            if(dis>0&&dis<=_alignmentDistMin){
                alignmentVectorSum+=other_velocity*(1.0/dis);
                alignmentCount++;
            }
            disMin=min(disMin,dis);
            disMax=max(disMax,dis);
            
        }

        GroupMemoryBarrierWithGroupSync();

    }


   

     if(joinCount>0){
        //joinForce
        joinForce.x=joinPosSum.x/(float)joinCount;
        joinForce.y=joinPosSum.y/(float)joinCount;
        joinForce.z=joinPosSum.z/(float)joinCount;
        joinForce=joinForce-my_position;
        joinForce=normalize(joinForce)*speed;
        
        result_velocity+=(float3)joinForce*_joinPower;
        
       
    }

     if(separateCount>0){
        //separateForce
        separateForce.x=separateVectorSum.x/(float)separateVectorSum;
        separateForce.y=separateVectorSum.y/(float)separateVectorSum;
        separateForce.z=separateVectorSum.z/(float)separateVectorSum;
        separateForce=separateForce-my_position;
        separateForce=normalize(separateForce)*speed;

      
        result_velocity+=(float3)separateForce*_separatePower;
        
        
    }

     if(alignmentCount>0){
        //alignmentForce
        alignmentForce.x=alignmentVectorSum.x/(float)alignmentCount;
        alignmentForce.y=alignmentVectorSum.y/(float)alignmentCount;
        alignmentForce.z=alignmentVectorSum.z/(float)alignmentCount;
        alignmentForce=alignmentForce-my_position;
        alignmentForce=normalize(alignmentForce)*speed;

        result_velocity+=(float3)alignmentForce*_alignmentPower;
    
    }
    float3 previous_result_velocity=result_velocity;
    result_velocity+=float3(rand(float2((float)DID.x,0.123))*2.0-1.0,rand(float2((float)DID,0.456))*2.0-1.0,rand(float2((float)DID,0.789))*2.0-1.0)*_NoiseValue;
    result_velocity=TurnButterfly(my_position,result_velocity,(float)DID.x);

    float3 noiseVector=normalize(cross(result_velocity,float3(0.,0.,1.)));
    noiseVector=noiseVector*perlinNoise(float2(_DTime,(float)DID.x))*0.2;
    result_velocity+=noiseVector;

    _boids_force_write[DID.x]=result_velocity;
    
    _debugBuffer[DID.x]=float4x4(float4(joinPosSum,0),float4(result_velocity,0),float4(previous_result_velocity,disMin),float4(joinCount,separateCount,alignmentCount,disMax));

}

[numthreads(NUMTHREADS_X_NUM,1,1)]
void ResultVector(
      uint3 GID : SV_GROUPTHREADID,
    uint3 DID : SV_DISPATCHTHREADID
){
    Butterfly boids_data=_boids_data_write[DID.x];
    float3 now_pos=boids_data.position;
    float3 now_vel=boids_data.velocity;

    float3 force=_boids_force_read[DID.x];
    
    float3 nex_vel=force;
    float3 next_pos=now_pos+normalize(nex_vel)*_DTime*50.0;
   
    boids_data.position=next_pos;
    boids_data.velocity=nex_vel;

    _boids_data_write[DID.x]=boids_data;
} 