#pragma kernel NextInputPos
#pragma kernel NodeInfo

struct Butterfly{
    float3 position;
    float3 velocity;
};

struct trail{
    int nextCalNodeIndex;
};

struct node{
    float3 node_position;
    float node_life;
};

 struct input_data{
    float3 nextInputPosition;
};

RWStructuredBuffer<Butterfly> _boids_data_read;
RWStructuredBuffer<input_data> _nextCalTrailPosition_write;
RWStructuredBuffer<input_data> _nextCalTrailPosition_read;
RWStructuredBuffer<trail> _trailIndexData_write;
RWStructuredBuffer<trail> _trailIndexData_read;
RWStructuredBuffer<node> _node_data_write;
RWStructuredBuffer<node> _node_data_read;

int _nodeSegment;

[numthreads(256,1,1)]
void NextInputPos(
    uint3 DID : SV_DISPATCHTHREADID
){
    _nextCalTrailPosition_write[DID.x].nextInputPosition=_boids_data_read[DID.x].position;
}

[numthreads(256,1,1)]
void NodeInfo(
    uint3 DID : SV_DISPATCHTHREADID
){

}
