#pragma kernel NextInputPos
#pragma kernel NodeInfo

struct Butterfly{
    float3 position;
    float3 velocity;
};

struct trail{
    int nextCalNodeIndex;
};

struct node{
    float3 node_position;
    float node_life;
    int renderFlag;
};

 struct input_data{
    float3 nextInputPosition;
};

RWStructuredBuffer<Butterfly> _boids_data_read;

RWStructuredBuffer<input_data> _nextCalTrailPosition_write;
RWStructuredBuffer<input_data> _nextCalTrailPosition_read;
RWStructuredBuffer<trail> _trailIndexData_write;
RWStructuredBuffer<trail> _trailIndexData_read;
RWStructuredBuffer<node> _node_data_write;
RWStructuredBuffer<node> _node_data_read;

RWStructuredBuffer<float4x4> _debug_buffer_node_position;

int _nodeSegment;
float _nodeDistanceMin;
float _DTime;

//numthreads変えるかも?
[numthreads(256,1,1)]
void NextInputPos(
    uint3 DID : SV_DISPATCHTHREADID
){
    _nextCalTrailPosition_write[DID.x].nextInputPosition=_boids_data_read[DID.x].position;
}

[numthreads(512,1,1)]
void NodeInfo(
    uint3 DID : SV_DISPATCHTHREADID
){
    //DID is now trail number
    // cal node index = _nodeSegment*DID+trail.nextCalNodeIndex
    //考えること
    //nextPositionの更新タイミング
    //node_lifeの扱いをどうするか
        //スレッド数を増やす？？ nodeの合計分のスレッド数??
        //１つのスレッドにつき、１つのnodeを計算する
        //スレッド数とグループ数について再考する
        
        //調査の結果、最大グループ数65535 グループ内の最大スレッド数が1024で　全体で約6700万スレッドを持てることがわかった
            //結論: １つのスレッドにつき、１つのnodeを計算する
            //それぞれのスレッドでpositionとlifeを計算する
            //DIDをもとにinput_positionとtrail_nextIndexのインデックスを割り出す必要がある
    
    //debug///////////////////

    /////////////////////////

    int myNodeIndexInBuffer=DID.x;
    int trailIndex=(int)(floor(DID.x/_nodeSegment));
    trail trainIndex_val=_trailIndexData_read[trailIndex];
    int nowCalNodeIndex=trainIndex_val.nextCalNodeIndex;
    int myNodeIndexInNodes=myNodeIndexInBuffer-trailIndex*_nodeSegment;

    input_data now_inputData=_nextCalTrailPosition_read[trailIndex];
    node now_node_data=_node_data_read[myNodeIndexInBuffer];

    int renderFlag=now_node_data.renderFlag;
   
    //if(false){
    if(renderFlag<0&&nowCalNodeIndex==myNodeIndexInNodes){
        renderFlag=renderFlag+1;
        now_node_data.renderFlag=renderFlag;
        _node_data_read[myNodeIndexInBuffer]=now_node_data;
        // _node_data_write[myNodeIndexInBuffer]=now_node_data;


    //     nowCalNodeIndex=nowCalNodeIndex+1;
    // trainIndex_val.nextCalNodeIndex=nowCalNodeIndex;
    // _trailIndexData_read[trailIndex]=trainIndex_val;
    }

    //if(false){
    if(nowCalNodeIndex==myNodeIndexInNodes){
         int previousIndex=trailIndex+(int)floor(fmod(myNodeIndexInNodes-1,_nodeSegment));
        float3 previousPos=_node_data_read[previousIndex].node_position;
        float betweenNodesDis=length(now_inputData.nextInputPosition-previousPos);

        // //debug
        // nowCalNodeIndex=nowCalNodeIndex+1;
        // trainIndex_val.nextCalNodeIndex=nowCalNodeIndex;
        // _trailIndexData_read[trailIndex]=trainIndex_val;
        
        //ここの条件に関するところがおかしい
        if(betweenNodesDis>=_nodeDistanceMin){
            now_node_data.node_position=now_inputData.nextInputPosition;
            now_node_data.node_life-=_DTime;

            _node_data_write[myNodeIndexInBuffer]=now_node_data;

            nowCalNodeIndex=nowCalNodeIndex+1;
            nowCalNodeIndex=(int)floor(fmod(nowCalNodeIndex,_nodeSegment));
            trainIndex_val.nextCalNodeIndex=nowCalNodeIndex;
            _trailIndexData_read[trailIndex]=trainIndex_val;

            // //debug
            // nowCalNodeIndex=nowCalNodeIndex+1;
            // trainIndex_val.nextCalNodeIndex=nowCalNodeIndex;
            // _trailIndexData_read[trailIndex]=trainIndex_val;
            
        }

       
    }

    // nowCalNodeIndex=nowCalNodeIndex+1;
    // trainIndex_val.nextCalNodeIndex=nowCalNodeIndex;
    // _trailIndexData_read[trailIndex]=trainIndex_val;


     
    float4x4 debug_matrix=float4x4(
        float4(now_node_data.node_position,renderFlag),
        float4(0.,0.,0.,0.),
        float4(0.,0.,renderFlag,0.),
        float4(myNodeIndexInBuffer,trailIndex,nowCalNodeIndex,myNodeIndexInNodes)
    );
    _debug_buffer_node_position[myNodeIndexInBuffer]=debug_matrix;
   
}
